### ISSUE TITLE
Update to Unity 2022.3... latest LTS

### ISSUE THREAD

**Issue by Tyroonis** [GothicVRProject/GothicVR#109]

**Comment by Tyroonis** [comment]
Will be processed following PR #108

**Comment by JaXt0r** [comment]
Sure, but I would recommend not putting any effort into it right now IF there's no change log item which brings us benefits. But I'm curious what you'll find.

**Comment by Tyroonis** [comment]
There have been some new versions of OpenXR and the OpenXR Oculus packages. Multiple.
For that reason alone it makes sense if we also want to support the new versions.

There were also improvements for URP, the burst compiler and IL2CPP. And also some bug fixes.

It's not a huge leap. It's an LTS update.

**Comment by JaXt0r** [comment]
Nice! You got me at "new versions". 🤣

Curious if everything will work with this version. Go on please.

**Comment by Tyroonis** [comment]
I'll test it one day
