### ISSUE TITLE
Skybox (e.g. barrier effects)

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#12]
Currently we leverage Directional Light only. But the result is, that night is pitch black in the sky. We need to check if we can have the real skybox from phoenix.

Hint:
OpenGothic has no barrier right now: https://github.com/Try/OpenGothic/issues/357

**Comment by Tyroonis** [comment]
Is there a skybox mesh?
Maybe we can make something nice with the skybox texture and shaders?
