### ISSUE TITLE
If GameSettings.json has wrong value for Gothic files, we need to show an error on screen

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#128]
Currently first gamers test our game, but they only get an empty nothing inside their HMD.

**Comment by Tyroonis** [comment]
Preferably a simple canvas in English.

![image](https://github.com/GothicVRProject/GothicVR/assets/12483468/304a9bd6-ab53-4fd1-b547-999d800d453c)

**Comment by JaXt0r** [comment]
This is great and easy to implement afaik. I especially like the part: Game destroys itself in 5...4...3... 🤣

**Comment by JaXt0r** [comment]
Done by @Romeeey in 2023. Also already shipped to first internal tester version. Closing issue now.
