### ISSUE TITLE
Add occlusion collider for all maps

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#143]
- [x] world
- [x] old mine
- [x] new mine
- [x] graveyard
- [x] sleeper temple
- [ ] (anything missed?)

- [ ] Test it, if it's used after loading

**Comment by JucanAndreiDaniel** [comment]
In #140 we already have added occlusion data for all the maps of G1, only G2 maps remain as of now

**Comment by JaXt0r** [comment]
@JucanAndreiDaniel I briefly checked: Occlusion data is named inside Unity Inspector for world.zen and oldmine.zen differently.

It's implemented in branch feature/world-triggers: https://github.com/GothicVRProject/GothicVR/tree/feature/world-triggers
