### ISSUE TITLE
Set Application.version for release builds.

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#194]
When we ship our game, we would like to have an option, that error logs tell us which version users have installed. (To not debug stuff which is fixed already in later versions etc.).

# What we have

FileLoggingHandler.cs
```csharp
fileWriter.WriteLine("GVR Version: " + Application.version);
```
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/7374853b-d349-4b07-8914-94d0e508603e)

This directly uses the version mentioned inside ProjectSettings/ProjectSettngs.asset --> bundleVersion: 0.1
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/f5b9ebf4-8dcf-45b2-8eee-7c6bc587c152)

# What we need

* We need a way, that the pipeline will change this value during Release build temporarily for this build (not pushing to repository).
* Whenever gamers send their error logs to us, we can then see the right version from their logs.

# Investigations

* GameCI has a flag for this, but I could't get it to use inside release.yml workflow pipeline. The log still mentioned the same 0.1 version.
* Docu: https://game.ci/docs/github/builder/#versioning

How to test:
* Create a new release
* Give it a tag value
* Wait for release pipeline to finish creating artifacts
* Test it locally

**Comment by Tyroonis** [comment]
I added an action before the actual build.
The version is adjusted locally in the Projectsettings.asset.

The version always has the name of the tag!!!

```
 # Set Version
      - name: set Version
        run: |
          ref="${{ github.ref }}"
          tag="${ref#refs/tags/}"
          echo "Version: $tag"
          sed -i "s/bundleVersion: 0.1/bundleVersion: $tag/"  ProjectSettings/ProjectSettings.asset
```

**Comment by Tyroonis** [comment]
@JaXt0r 
Is that OK?
Had to do it directly in the main so I can test it.
There is no separate branch.

If OK, the issue can be closed

**Comment by JaXt0r** [comment]
Super straight forward! Didn't think of this low level way. Super cool. Approved.

**Comment by Tyroonis** [comment]
- Test Release removed
- Issue closed
