### ISSUE TITLE
Pipeline - Set default values

### ISSUE THREAD

**Issue by Tyroonis** [GothicVRProject/GothicVR#197]
Pipeline should set the feature flags correctly when building and, if necessary, check whether the VR player is selected.

Reason:
If a developer pulls the status with debug flags or activated flat player, the pipeline corrects this so that the build is also playable on the glasses.

_Additive:_

_Set flag in commit or label if flags should not be corrected_

**Comment by JaXt0r** [comment]
This is done. When releasing, we call the Menu item: "GothicVR/Tools/FeatureFlags - Set Production ready state" in FeatureFlagTool.cs
