### ISSUE TITLE
Create APK for Pico4/Quest2 and test if DLL/SO is working

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#2]
> Beware of #3 as Windows builds are also not working as of now. Once fixed, we can work on this ticket.

We need to test if a .so /.dll build is also loaded for APK builds.

As debugging can be quite a pain, here are some ideas how to iteratively work on it:

Debugging:
* Add writing to an error.log on Unity side to get details about DLL issues.
* Add same logging on bridge side

Call "simple" methods:
1. Call a "testHelloWorld" method from the DLL which is returning an int and check if Unity fails.
2. Create a new dll project where you only have the "testHelloWorld" as function to ensure that no "other library is missing within the dll".

**Comment by JaXt0r** [comment]
@lmichaelis checked our build on Linux already. .so got loaded and world was parsed+shown successfully. ✅
(i.e. build works for Linux systems.)

We now need to test ARM64 for pico and Quest2 OS only.

**Comment by JaXt0r** [comment]
@Tyroonis works, tight? Can we close this one?

**Comment by Tyroonis** [comment]
Yes we can close.
The improvement takes place in #22
