### ISSUE TITLE
Add interactions: Chair, Bank, Bed

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#227]
Let's add more interactions with the world, based on what we load to the game already. An easy but immersive feature could be to sit/lie on vobs as original Gothic is offering.

I suggest the following workflow:
1. We "select" the object (similar to how we interact with ladders for example)
2. Then we "blink" to the object

Blink refers to a black fading out and fading in mechanism. To overcome nausea when we move and turn the player to sit down etc.

![2023-10-13 07_31_25-Amazon Photos](https://github.com/GothicVRProject/GothicVR/assets/120568393/41b1699a-269e-44bc-a9c6-296ce209a1eb)

Hints:
Let's focus on the following elements: chair, bench, bed
(and lat but not least the barrel left side when entering OC, where you can hide. Will be a nice easter egg)
* All of these vobs have so called Slots. (ZS_*) We can easily use their location+rotation to move the player to this spot where we want him to sit.

**Comment by piotrb92** [comment]
almost done now just need to set correct position and rotation offset and test.
