### ISSUE TITLE
Menu: Slider for Music and Sound volume + Button for Music on/off

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#231]
Just plain settings like original gothic game has. ;-)

![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/b9d4a727-b4c1-4cf4-b105-db1c576a7f45)

**Comment by JaXt0r** [comment]
@JucanAndreiDaniel fixed?

**Comment by JucanAndreiDaniel** [comment]
2/3 only since we dont have a button for on/off music

**Comment by JaXt0r** [comment]
All good. Can be closed as of now.
