### ISSUE TITLE
Routine Waypoint Based Pathfinding

### ISSUE THREAD

**Issue by Frozenenenen** [GothicVRProject/GothicVR#242]
On how I intend to approach the Waypoint based pathfining for NPC Routines.

**Comment by Frozenenenen** [comment]
Expand on Waypoint data:
![image](https://github.com/GothicVRProject/GothicVR/assets/85682798/03937172-127b-4664-bb05-6abda0da7e4e)

To do this I'll create a new _**temporary**_ dictionary of waypoints, which encompass the original waypoint (wp) data and expand it by new values.
These values are:
The Weighting - This means distance to the current goal wp. This actually doesnt necessarily need to be safed, since it mostly need to be calculated anew every time anyways, so its not all that useful to safe it.
The Distance - sum of the distance of all egdes until the current wp.

Dijkstra with weighting (a algorithm with A* is based on) will be used to find the way from start to destination. A list will be created if the way is found. This list will be conected to the corresponding routine.

Every NPC get one of theses new list of wp per routine.
They'll be safed as long as the game runs. Each time a routine changes another list will be connected/loaded. If the NPC starts a routine it will run to the next wp in the list, until it reaches it.
To see if it reached the wp, there need to be some kind of trigger there. This could be done by distance check or a invisiable cube, that triggers, if entered. I plan on doint the letter with invisible trigger boxes.

If entered the counter on the wp-list will be upped (++), so the next wp can be targeted. If the last element of the list is active, the NPC will stay there.


What not to expect (yet):
NPC will not go near the wp to create some kind of "camp" where several NPCs stand close to each other. They'll stand IN each other, if they have the same goal at the same time. (I dont think this is the case with the waynet system though)
NPCs will not look at each other, after arriving (I have no idea right now where looking direction information ins saved in)
they'll probably not look in the direction they are flying to.
No walking animation(s).

**Comment by Frozenenenen** [comment]
About Dijkstra with weighting:

Covered distance is preset as max or at least a very hight value, that cant be reached.

From the Source each connnected WP will be checked. For each the distance to the goal and the covered distance will be added together. The sum of both will indicate how good the value is. the smaller the better.
Each point will get a "previous WP" or "Father WP" to be able to reproduce the way later.

The Point with the lowest sum of covered distance and distance to goal will be the next.

Like with the first WP, every connected WP (except the father) will be checked for a distance to goal and covered distance.

If the covered distance is smaller than the value thats already calculated, it will be changed to the new value.

Again for each WP the sum of covered distance and distance to goal will be calculated. 
Again the smallest WP will be the next.

Repeat until you find the destination point.


When the destination is found a list of all father WPs one after another until the start point will be created.

**Comment by Frozenenenen** [comment]
![image](https://github.com/GothicVRProject/GothicVR/assets/85682798/4e65c55e-4702-454e-9e5b-cb6b644af4aa)

**Comment by Frozenenenen** [comment]
Okay the one above is actually wrong.

I just checked for the smallest in the last set of neighbor waypoints, but all waypoints need to be cheked.

I inted to do this with a list where all waypoints get put into and always sort by the distance sum.
The smallest will always be taken and then deleted from the list.

There need to be some kind of measure so that elemts, that are in the list cant be added again later. idk yet.

**Comment by Frozenenenen** [comment]
`namespace GVR
{
    public class DijkstraWaypoint
    {
        public string name = "";                                //as index to find other data like position, underwater and probably isFree

        public double coveredDistance = 0;

        public double summedDistance = 0;

        public List<string> neighbors = new List<string>();

        public string fatherWP = "";
    }
}
`
Added the summed distance, because the WPs are sorted by it.
Deleted Distance to destination, since it cant be efficiently calculated beforehand, since every routine has another destination.
Its just needed to get the sum anyway, so its stuffient to do it temporary.
Covered distance on the other hand has to be passed to the child WP to be calculated again.

**Comment by Frozenenenen** [comment]
And another try

![image](https://github.com/GothicVRProject/GothicVR/assets/85682798/3987f408-9a1b-475c-9824-412991a2786e)

![image](https://github.com/GothicVRProject/GothicVR/assets/85682798/cd58c461-f680-499e-b3ce-283584ee1a6b)

**Comment by JaXt0r** [comment]
One more thing: Please consider OpenGothic's implementation. Maybe we can reuse it or at least learn from it.
https://github.com/Try/OpenGothic/blob/master/game/world/waymatrix.cpp#L285-L370
