### ISSUE TITLE
Discord link is expired

### ISSUE THREAD

**Issue by noomorph** [GothicVRProject/GothicVR#278]
![image](https://github.com/GothicVRProject/GothicVR/assets/1962469/d4232277-0017-4552-9ed1-69e0d465f1bf)

**Comment by JaXt0r** [comment]
Good catch. Thanks. We rearranged our invitation links now.
GitHub repository and YouTube channel will now work with the latest one.

Please use this one and try again.
https://discord.gg/StV9pbkBer

See you in Discord. 👋
