### ISSUE TITLE
Item stays visible when "put away" animation is played

### ISSUE THREAD

**Issue by Romeeey** [GothicVRProject/GothicVR#345]
1.) Watch NPC 324 (schatten) or NPC 554 (buddler)
2.) The NPC will eat bread 
3.) The "put away" item is played
4.) The bread is still in his hands.

Expected behaviour: 
The item should vanish

**Comment by JaXt0r** [comment]
Please retest. I can't reproduce it.

* The NPC 324 is Balam, a cook which is not eating.
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/d34ebd18-f8de-430a-84a9-314adeb38d2b)

* The NPC 554 and 535 are eating. I watched them for over a minute and they always remove their old item whenever they eat something new.
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/0f3af8d9-2e59-4e1b-a65e-11cf2fd630c2)

It seems you didn't use the latest version as I fixed it with this commit: https://github.com/GothicVRProject/GothicVR/pull/342/commits/8a7e0941add5c3e65f067babfbbd9b22b2bae66c

**Comment by Romeeey** [comment]
Retested and works with current version.
Ticket closed.
