### ISSUE TITLE
Item Import Editor Tool

### ISSUE THREAD

**Issue by Tyroonis** [GothicVRProject/GothicVR#41]
We will have to customize almost every item, or at least the core prefab.
Or the Scriptable Object?!  (I would like it better).

Now it would be cool, if the editor (above) in the guide would have an item called Import.
Under this point is then a list of all items.

When clicked, the Prefab/Scriptable Object should be loaded and the appropriate Mesh imported and attached.
So you can adjust the prefab/scriptable object and see the model. So you don't have to build blindly.
This would be especially useful for objects where you have to adjust the grab point.

_This "tool" could later be used by modders to customize it for their items._

Would just simplify the customization extremely.
You don't have to build every prefab blindly and test it in playmode.

**The list would also have to be loaded dynamically**

**Comment by JaXt0r** [comment]
I think of the following workflow:
1. You click on a menu item in editor called "ImportSingleItem" or so
2. It will then open a popup for you where you select the actual item to import based on list of known items.
3. It will then open a new temp scene where only this item is being imported, attached to a prefab, and shown in Scene view.
4. You can then edit settings in Editor, change Prefab and save, and alter the import script to your needs.

**Comment by Tyroonis** [comment]
I think it's good.

Possibly after selecting a check can be made whether there is already a prefab / SO
If so, this is loaded for editing.

If not, a 2 popup window appears to create a new Sriptable Object.
I can then take over the new create.

**Only the item in a tmp. Scene.**

**Comment by JaXt0r** [comment]
I implemented loading all of the items by name. Once https://github.com/GothicKit/phoenix-csharp-interface/pull/10 is merged (and you downloaded the latest .dll from phoenix-shared), you can use the following methods:

```C#
    string[] itemNames = PbVmGetInstancesByClassName(vmPtr, "C_Item");
    var items = List<PxVmItemData>(itemNames.Length);
    
    foreach(var itemName: itemNames) {
        items.Add(PxVm.InitializeItem(vmPtr, itemName));
    }
    
    // Hint: Now you have all the items which are placed in the world, pockets, chests, etc.
    // But there will be items, which have the same visual name. So you need to see what to do. ;-)
    
    // Create items by using this property
    foreach(var item: items) {
        var mrm = assetCache.TryGetMRM(item].visual);
        var gameObject = meshCreator.Create(..., mrm ,...);
    }
```

**Comment by JaXt0r** [comment]
New idea: Have a separate scene where we have
1. UI buttons to spawn an Item
2. A plate where the item is spawned
3. Slider for the grab position values
4. Test changes live
5. Save settings for the item


Use some start scene like this one https://www.youtube.com/watch?v=dCVAYB2jkEY&ab_channel=ValemTutorials

**Comment by JaXt0r** [comment]
The scene is implemented.
It's Lab.unity

There we build the system to define specific grab points via Sliders and buttons. The data is stored on JSON files.
But in parallel we found an intermediate solution for dynamicAttach (feature from OpenXR). With this, we will park this topic for now and will reassess later if needed.

I will close the ticket for now. Feel free to reopen if needed.
