### ISSUE TITLE
NPC routines - Improve performance and routing

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#5]
NPC Routines currently cost about 140 fps. ¯\_(ツ)_/¯

As it was created in a hurry, we need to improve it:
* [ ] NPCs need to walk along the WwaypointEdges
* [ ] improve performance

**Files of interest:**
* [WorldBridge.cs:_GetWorldWaypoints()](https://github.com/GothicVRProject/unZENity-VR/blob/main/Assets/unZENity-VR/Scripts/Phoenix/Bridge/WorldBridge.cs#L140) - Function(s) where the Waypoints and WaypointEdges are fetched from DLL.
* [Routines.cs](https://github.com/GothicVRProject/unZENity-VR/blob/main/Assets/unZENity-VR/Scripts/Npc/Routine.cs) - Actual routine check every frame

**NPC with Routine**
I recommend you check with Bloodwyn. He has 7 routines which will give you one of the most complex examples to improve.
![image](https://user-images.githubusercontent.com/120568393/228445452-bbbdc2c6-116c-4396-a103-766818939ff2.png)

**WaypointEdges**
Waynet system which is intended for Gothic NPCs to walk from Waypoint to Waypoint instead of skipping the path and directly move to end Waypoint.

![image](https://user-images.githubusercontent.com/120568393/228445644-ab985cf2-e0fb-4d24-97fa-fa6dfe2d9584.png)

**Comment by Frozenenenen** [comment]
Performanceupdates:
The Waypoints List was extended by a Dictionary of the same data to be able to find Vector3 data faster without looking through the whole list, every time a new routine starts.
I further added an eventsystem that sends ticks every ingame minute (irl ~6s) making the routine and waypoint lookup way mire infrequent.

**Comment by Frozenenenen** [comment]
Next up is a system that handles the routines at one place and calls seperate NPC routinesLookUps, when they are due.

If this is done I'll look for the way to walk the NPCs along the waypoint edges.

**Comment by JaXt0r** [comment]
What's the benefit of centralized handling "when an NPC is done walking?".

I mean they will walk their way. Once they arrived, they stop walking (on their own). Then they only listen to new minute events and need to check if they need to change routines. Please explain your central enhancement. Maybe I'm missing the point. 😋

**Comment by Frozenenenen** [comment]
Now every! NPC is asked every 6 seconds if he has a routine. 
if so he will look through the routines list. (This will call every NPC indpendend of if he has reached his goal or is moving atm)
 and accordingly the waypoints dictionary.
 
 If it is handled in one spot this method will do something every ingame minute. But the NPCs will just be called about every 2 minutes (this is, because routines normally just start every 15 ingame minutes) and just the ones that really have a changed routine.  This will decrease the calculation at the NPCs to a minimum. The question is how much performance the RoutineManager will actually use. hard to say by now. I guess this will be less than every NPC looking through his routines at last.
 
 ATM the Timeticks of every 6seconds drops the fps by about a little bit above 10% (~120-105fps on my system in flatscreen unity). Especially one frame is way too long.

**Comment by Frozenenenen** [comment]
Another open point ist that NPC atm move to their goal even if they already reached it. this will be addressed together with the walking about waypoint edges.

**Comment by JaXt0r** [comment]
Ah I get it. So
1. You see that performance needs to be further improved (the 10% example) - justification is there
2. The centralized manager could take care of pinging NPCs only if needed.

Ok. I agree now.
A suggestion: Use this NpcRlutineManager to
1. Keep a dictionary of NPCs which needs to be informed at which ingame minute
2. Listen to every ingame minute event
3. Only call the NPCs to "change" their routines if the Manager found their entry at this exact ingame minute.

This means only a handful of NPCs get called within a few ingame minutes.

Smart. 🫡

**Comment by JaXt0r** [comment]
Caching sounds great. Let's start with it and do a performance test how long it will take for the old Camp NPCs to load their waypoints/routes. If it's more than a second, we could thing about more.

Hint: You can use a Watch() to Print the consumed time. Look at PhoenixImporter.cs around line 10-20 for an example.

But for now (as there are no data points if it's needed), I would argue against the separation of waypoints:
1. I saw with VOBs: The naming scheme isn't 100% right. (E.g. OC isn't always old Camp)
2. We would be highly dependent on Gothic one. Changes for Gothic 2 and mods would be more complex.
3. There are people walking from psi camp to old Camp. You would need to separate their logic.
4. What if e.g. the outer old Camp area isn't OC-...? Then your algorithm would look through all OC waypoints, finding no result and redo with non OC ones? Could be a Performance "Verschlimmbesserung"🤣
5. The A* algorithm normally doesn't need to look a long way. There are normally only 2-5 attached waypoints to another. So the algorithm should be fast and only needs to be called once.
6. Is there really a need for this improvement? I mean it will add more complexity, obfuscated code (might be), and it could be a potential premature optimization.

**Comment by JaXt0r** [comment]
Routines are implemented and working since ~November 2023.
