### ISSUE TITLE
Worldmusic - Play gothic music track

### ISSUE THREAD

**Issue by JaXt0r** [GothicVRProject/GothicVR#6]
We want to have Gothic music being played when walking through the barrier.
* [x] Check within [phoenix](https://github.com/lmichaelis/phoenix/tree/30179d81a678f8a36fbaf3306a443f779520a0a0) and [OpenGothic](https://github.com/Try/OpenGothic) how it was loaded there
* [x] Build a bridging functionality to load the track from C++ into C#
* [x] Store the binary wav stream in a (e.g.) Unity AudioClip and play
* [x] Create VOB with triggers to play music in a dynamic way
* [x] Create object to handle and music state and change

Boundary:
This ticket does not include dynamic track change. A first atmospheric and iconic gothic sound would be awesome. ♥

Hint:
Gothic leverages music as DirectMusic format. We need to check if it's
1. possible to use within Unity,
2. buy an asset to have it parsed, or
3. rebuild ffmpeg/OpenGothic's implementation: https://github.com/Try/OpenGothic/tree/master/game/dmusic

**Comment by JucanAndreiDaniel** [comment]
http://www.vgmpf.com/Wiki/index.php?title=SGT
http://www.vgmpf.com/Wiki/index.php?title=STY
http://www.vgmpf.com/Wiki/index.php?title=DLS
Some documentation which shows the RIFF Tree Structure of the music formats used in Gothic

https://documentation.help/DirectMusic/  - docs for everything related to DirectMusic (inferred from what I skimmed through)

**Comment by JucanAndreiDaniel** [comment]
Checked the original tasks and added some more to reflect current progress
